"========== compatibility ==========
set guioptions=
set mouse=
set nocompatible
set fileencodings=utf8
set guicursor=a:blinkon0

" NOTE
" if fs is not persistent, swap/backup files are useless
" if fs is remote, swap/backup files mean lots of network traffic
set noswapfile
set nobackup
set nowritebackup

"========== sane defaults ==========
set ruler
set number
set wildmenu
set nocomatible
set backspace=indent,eol,start
set wildmode=longest,list,full

set expandtab
set shiftwidth=4
set tabstop=4

"========== default appearance ==========
set guifont=12px\ \"Source\ Code\ Pro\"\\,monospace
colorscheme codeschool
syntax on
